server:
  port: 8083
logging:
  level:
    root: info
    icu.baidu.aria2: info
spring:
  cache:
    type: caffeine
baidu:
  remove-prefix: 百度网盘
  share-link-pwd: 9527
  app-id: 250xxx
  cookie: BAIDUID=84E2BFB882EAD2598C05xxxxBBA588:FG=1; BAIDUID_BFESS=84E2BFBxxxxxx1053BBA588:FG=1; csrfToken=9woVLtZeE9IF4nA_rqgocl3P; newlogin=1; BDUSS=XN3aTRBTDJwdn5IWWJGN2l6LWRBdmZhMkRDaHY0MXFTMGhxSXptd0xRTlVGYUZqSVFBQUFBJCQAAAAAAAAAAAEAAAA9cMOPub3BubrDu6y~7LzQvfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxxxxNUiHlje; BDUSS_BFESS=XN3aTRBTDJwdn5IWWJGNxxxxxTMGhxSXptd0xRTlVGYUZqSVFBQUxxxxAAAAAAAAAAAEAAAA9cMOPub3BubrDu6y~7LzQvfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFSIeWNUiHlje; STOKEN=01c3b5d1bacaf726938aa26eb8afd0ca7908313078ad65ebf72da756129b0aeb; PANPSC=124653089xxxxD8%2BbSuXlibiKzYuqjC14bcoQ3Rb16E6HpLI5T5C%2FyiR6%2Frxxxf6sRWrHWTitSOA6%2BHHtciFfRxz%2FZnirvP3pcJ689LEAIReFB47CbU9vHkRFzk38adFcn1Zflfd6NEFB3kkm1IYWWwAi260CAi3Ua%2FmHyIq%2FPkL2qAeJq7%2BV1Lxzud0jMsTEZmK5RR4JqhfSnrP2UPxXuD7k8za9a6w%3D%3D; ndut_fmt=141E6CFB27FC83A2CE67753E37341AF4E0E4F45F5AB4E6421448BCD37BA10783; ab_sr=1.0.1_NThkZDIxOTMzOWUwNmUyYmIyNDVkMjZiNzRjZGI0NzZlMWUyZjkwMmQ0NTMwOTBlMTU3NjczZDJmNTI0NDQ4xxx2IwYzM3MjVlYzg4MjZiYWViNzI0MDYwZjljNTBiMWY1NWEwMDg3NzRhMWEyNjA3OTA4MGQwNWViODM4ZWJlMDk0NmMwYWMwNDQwY2RmZGM0MmQ0MWY1MDZkNTNlZTZjZjkwZTVjODU5NDFk
  dp-log-id: 207560004458892xxx
dnspod:
  enabled: true
  domain: icu-xxx.tk
  record-id: 125468xxx
  secret-id: AKIDHf3AEHJJG9xdaLvMcJm0yf9Oxxx
  secret-key: RdaKDqJYXHo7B3h6HDvqdLzxumXxx
