server:
  port: 8083
logging:
  level:
    root: info
    icu.baidu.aria2: info
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
baidu:
  remove-prefix: 百度网盘
  share-link-pwd: 9527
  app-id: 250528
  cookie: BAIDUID=xxx98C05771053BBA588:FG=1; BAIDUID_BFESS=84E2BFxxx053BBA588:FG=1; csrfToken=9woVLtZxxxF4nA_rqgocl3P; newlogin=1; BDUSS=XN3aTRBTDJwdn5IWWJGNxxxxGhxSXptd0xRTlVGYUZqSVFBQUFBJCQAAAAAAAAAAAEAAAA9xxxDu6y~7LzQvfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxxxUiHlje; BDUSS_BFESS=XN3aTRBTDJwdn5IWWJGN2l6LWRBdmZhMkRDaHY0MXFTMGhxSXptd0xRTlVGYUZqSVFBQUFBJCQAAAAAAAAAAAEAAAA9cMOPub3BubrDu6y~7LzQvfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxxxxAAAAFSIeWNUiHlje; STOKEN=01c3b5d1bacaf726938aa26eb8afd0xxxx6129b0aeb; PANPSC=12465308xxxAKkwrx6t0uHB2bMxD8%2BbSuXlibiKzYuqjC14bcoQ3Rb16E6HpLI5T5C%2FyiR6%2FrXp563bR7esl%2BvbUEC3RmUNHf6sRWrHWTitSOA6%2BHxxxxeFB47CbU9vHkRFzk38adFcn1Zflfd6NEFB3kkm1xxxHyIq%2FPkL2qAexxxa6w%3D%3D; ndut_fmt=141E6CFB27FC83A2CE67753E37341AF4E0E4Fxxx421448BCD37BA10783; ab_sr=1.0.1_NThkZDxxxUyYmIyNDVkMjZiNzRjZGI0NzZlMWUyZjkwMmQ0NTMwOTBlMTU3NjczZDJmNTI0NDQ4MzA4xxxc4ZmYyM2IwYzM3MjVlYzg4MjZiYWViNzI0MDYwZjljNTBiMWY1NWEwMDg3NzRhMWEyNjA3OTA4MGQwNWViODM4ZWJlMDk0NxxxNTNlZTZjZjkwZTVjODU5NDFk
  dp-log-id: 20756000445xxxxxxx
dnspod:
  domain: icu-xxx.xx
  record-id: 12546xxxx
  secret-id: AKIDHf3AEHJJG9xdaLvMcJm0yf9Oxxxxxx
  secret-key: RdaKDqJYXHo7B3h6HDvqdLzxumXxxxxx
